[package]
name = "do-not-publish/template-fpf-rojo-project"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "data-oriented-house/lemonsignal@1.2.0"